### ISSUE TITLE
TODO for v1.1

### ISSUE THREAD

**Issue by IbraheemR** [OBANx/PAKit#1]
- [x]Min windown design & integration
  - [ ] Need to fix error
- [x] StdOut mode
- [ ]  Shortcut integration in registry etc. on install
  - [ ] Research windows
  - [ ] Research mac/linux
